steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args: [
      '-c',
      'docker build --no-cache -f=Dockerfile . --build-arg NUXT_STORAGE_PASSWORD=$$NUXT_STORAGE_PASSWORD --build-arg DIRECTUS_SERVER_TOKEN=$$DIRECTUS_SERVER_TOKEN -t $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      '
    ]
    id: Build
    secretEnv: ['NUXT_STORAGE_PASSWORD','DIRECTUS_SERVER_TOKEN']  
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: Deploy
    entrypoint: bash
    args: [
      '-c', 
      'gcloud run deploy $_SERVICE_NAME --image $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA 
      --region $_DEPLOY_REGION
      --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      --quiet
      --platform=managed
      '
    ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NUXT_STORAGE_PASSWORD/versions/latest
    env: 'NUXT_STORAGE_PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/DIRECTUS_SERVER_TOKEN/versions/latest
    env: 'DIRECTUS_SERVER_TOKEN'
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: europe-west2-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 83ba6948-e038-491e-996c-df889b17d57f
  _SERVICE_NAME: storefront-ui
  _DEPLOY_REGION: europe-west2
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - storefront-ui