ARG NODE_VERSION=22
ARG YARN_VERSION=3.6.1

FROM node:${NODE_VERSION}-slim AS base

ENV DOCKER_BUILDKIT=1

RUN yarn set version ${YARN_VERSION}
WORKDIR /src

# Build
FROM base AS build


ARG NUXT_PUBLIC_ODOO_BASE_URL="https://odoo.motorsport-tools.co.uk/"
ARG NUXT_PUBLIC_ODOO_BASE_IMAGE_URL="https://odoo.motorsport-tools.co.uk/"
ARG REDIS_URL="redis://10.154.0.2:6379"
ARG NUXT_STORAGE_URL="redis://10.154.0.2:6379"
ARG DIRECTUS_URL="https://dir.motorsport-tools.co.uk"
ARG PORT=3000
ARG NUXT_STORAGE_PASSWORD

ENV NODE_ENV=production
ENV NUXT_PUBLIC_ODOO_BASE_URL=${NUXT_PUBLIC_ODOO_BASE_URL}
ENV NUXT_PUBLIC_ODOO_BASE_IMAGE_URL=${NUXT_PUBLIC_ODOO_BASE_IMAGE_URL}
ENV REDIS_URL=${REDIS_URL}
ENV DIRECTUS_URL=${DIRECTUS_URL}

ENV NUXT_TELEMETRY_DISABLED=1
ENV NUXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=1
ENV NUXT_STORAGE_PASSWORD=${NUXT_STORAGE_PASSWORD}
ENV NUXT_STORAGE_DRIVER=redis
ENV NUXT_STORAGE_URL=${NUXT_STORAGE_URL}

ENV NUXT_STORAGE_INVALIDATION_KEY=123
# Currency
ENV NUXT_PUBLIC_CURRENCY_SEPARATOR="."
ENV NUXT_PUBLIC_CURRENCY_DECIMAL="."
ENV NUXT_PUBLIC_CURRENCY_SYMBOL="£"
ENV NUXT_PUBLIC_CURRENCY_PRECISION=2

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

#Livechat
ENV NUXT_PUBLIC_LIVECHAT_CHANNEL_ID=1

#Route GeneratorAdd commentMore actions
ENV NUXT_PUBLIC_CATEGORY_PAGE_SIZE=10000
ENV NUXT_PUBLIC_PRODUCT_PAGE_SIZE=10000

ENV NUXT_NODE_LOCALE="en-EN"
ENV NUXT_PUBLIC_VSF_PORT=443
ENV NUXT_SWR_CACHE_TIME=3600

COPY . ./
RUN yarn install --frozen-lockfile
RUN yarn build

#RUN yarn add -W nuxt \
#    && yarn \
#    && yarn build

# Run
FROM base

ARG NUXT_STORAGE_URL="redis://10.154.0.2:6379"
ARG NUXT_PUBLIC_ODOO_BASE_URL="https://odoo.motorsport-tools.co.uk/"
ARG NUXT_PUBLIC_ODOO_BASE_IMAGE_URL="https://odoo.motorsport-tools.co.uk/"
ARG DIRECTUS_URL="https://dir.motorsport-tools.co.uk"

ARG PORT=3000
ARG NUXT_STORAGE_PASSWORD

ENV NODE_ENV=production
ENV NUXT_PUBLIC_ODOO_BASE_URL=${NUXT_PUBLIC_ODOO_BASE_URL}
ENV NUXT_PUBLIC_ODOO_BASE_IMAGE_URL=${NUXT_PUBLIC_ODOO_BASE_IMAGE_URL}
ENV DIRECTUS_URL=${DIRECTUS_URL}
ENV NUXT_TELEMETRY_DISABLED=1
ENV NUXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=1
ENV NUXT_STORAGE_PASSWORD=${NUXT_STORAGE_PASSWORD}

ENV NUXT_STORAGE_DRIVER=redis
ENV NUXT_STORAGE_URL=${NUXT_STORAGE_URL}
ENV NUXT_STORAGE_INVALIDATION_KEY=123
# Currency
ENV NUXT_PUBLIC_CURRENCY_SEPARATOR="."
ENV NUXT_PUBLIC_CURRENCY_DECIMAL="."
ENV NUXT_PUBLIC_CURRENCY_SYMBOL="£"
ENV NUXT_PUBLIC_CURRENCY_PRECISION=2

#Route GeneratorAdd commentMore actions
ENV NUXT_PUBLIC_CATEGORY_PAGE_SIZE=10000
ENV NUXT_PUBLIC_PRODUCT_PAGE_SIZE=10000

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

ENV NUXT_CLARITY_ID="qccsf293te"
ENV NUXT_PUBLIC_LIVECHAT_CHANNEL_ID=1

COPY --from=build /src/.output ./

# Expose both ports
ENV HOST=0.0.0.0
EXPOSE $PORT
#EXPOSE 6379
EXPOSE 443

# Specify the command to run your app
CMD [ "node", "/src/server/index.mjs" ]
